export const FRONT_PATH = {
  ROOT: '/',
  DASHBOARD: '/dashboard',
  DROPS: '/drops',
  DROPS_CLAIM: '/drops/claim',
  DROPS_CLAIM_HISTORY: '/drops/claim/history',
  CORE: '/core',
  CORE_ASSET: '/core/asset',
  CORE_RETRIEVE: '/core/retrieve',
  CORE_SALE: '/core/sale',
  CORE_REFERRAL: '/core/referral',
  GEAR: '/gear',
  GEAR_WRAP: '/gear/wrap',
  GEAR_LOCKUP: '/gear/lockup',
  LAUNCHPAD: '/launchpad',
}